spring.application.name=jobtrackr-api

spring.datasource.url=jdbc:postgresql://localhost:5433/jobtrackr_db
spring.datasource.username=jobtrackr_user
spring.datasource.password=jobtrackr_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080